class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = '/mnt/mvt-rgbd/MVT'    # Base directory for saving network checkpoints.
        self.tensorboard_dir = '/mnt/mvt-rgbd/MVT/tensorboard'    # Directory for tensorboard files.
        self.pretrained_networks = '/mnt/mvt-rgbd/MVT/pretrained_networks'
        self.lasot_dir = '/mnt/mvt-rgbd/data/lasot'
        self.got10k_dir = '/mnt/mvt-rgbd/data/got10k/train'
        self.got10k_val_dir = '/mnt/mvt-rgbd/data/got10k/val'
        self.lasot_lmdb_dir = '/mnt/mvt-rgbd/data/lasot_lmdb'
        self.got10k_lmdb_dir = '/mnt/mvt-rgbd/data/got10k_lmdb'
        self.trackingnet_dir = '/mnt/mvt-rgbd/data/trackingnet'
        self.trackingnet_lmdb_dir = '/mnt/mvt-rgbd/data/trackingnet_lmdb'
        self.coco_dir = '/mnt/mvt-rgbd/data/coco'
        self.coco_lmdb_dir = '/mnt/mvt-rgbd/data/coco_lmdb'
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = '/mnt/mvt-rgbd/data/vid'
        self.imagenet_lmdb_dir = '/mnt/mvt-rgbd/data/vid_lmdb'
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
        self.davis_dir = ''
        self.youtubevos_dir = ''
        self.depthtrack_train_dir = '/mnt/mvt-rgbd/data/depthtrack/train'
        self.depthtrack_test_dir = '/mnt/mvt-rgbd/data/depthtrack/test'
